export const slugify = (text: string): string => {
  // ... (весь код функції slugify)
  const cyrillicMap: { [key: string]: string } = {
    а: 'a',
    б: 'b',
    в: 'v',
    г: 'h',
    ґ: 'g',
    д: 'd',
    е: 'e',
    є: 'ye',
    ж: 'zh',
    з: 'z',
    и: 'y',
    і: 'i',
    ї: 'yi',
    й: 'y',
    к: 'k',
    л: 'l',
    м: 'm',
    н: 'n',
    о: 'o',
    п: 'p',
    р: 'r',
    с: 's',
    т: 't',
    у: 'u',
    ф: 'f',
    х: 'kh',
    ц: 'ts',
    ч: 'ch',
    ш: 'sh',
    щ: 'shch',
    ь: '',
    ю: 'yu',
    я: 'ya',
    А: 'A',
    Б: 'B',
    В: 'V',
    Г: 'H',
    Ґ: 'G',
    Д: 'D',
    Е: 'E',
    Є: 'YE',
    Ж: 'ZH',
    З: 'Z',
    И: 'Y',
    І: 'I',
    Ї: 'YI',
    Й: 'Y',
    К: 'K',
    Л: 'L',
    М: 'M',
    Н: 'N',
    О: 'O',
    П: 'P',
    Р: 'R',
    С: 'S',
    Т: 'T',
    У: 'U',
    Ф: 'F',
    Х: 'KH',
    Ц: 'TS',
    Ч: 'CH',
    Ш: 'SH',
    Щ: 'SHCH',
    Ь: '',
    Ю: 'YU',
    Я: 'YA',
  };

  return text
    .split('')
    .map((char) => cyrillicMap[char] || char)
    .join('')
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^-a-z0-9]/g, '')
    .replace(/--+/g, '-');
};
